homeassistant:
  access_token: YOUR ACCESS TOKEN HERE
  url: http://homeassistant.local:8123/api
update_interval_sec: 600 # 10 minutes
  - name: Outdoor Temp
    entity_id: sensor.openweathermap_temperature
  - name: Outdoor Humidity
    entity_id: sensor.openweathermap_humidity
  - name: Forecast Temp
    entity_id: weather.openweathermap
    config:
      forecast:
        index: 1
        attribute: temperature
